server:
  port: 8081
spring:
  application:
    name: kopis-back
  datasource:
    url: jdbc:postgresql://kopis-db:5432/kopis
    username: admin
    password: kopis1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
logging:
  level:
    com.kopis.kopisback: debug
app:
  frontUrl: http://localhost:3001
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.kopis.kopisback