version: '1.0'

services:
  database:
    image: mysql:latest
    container_name: kopis-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kopis1234
      MYSQL_DATABASE: kopis
      MYSQL_USER: admin
      MYSQL_PASSWORD: kopis1234
    volumes:
      - kopisDB:/var/lib/mysql
  backend:
    build:
      context: kopis-back/build/libs
      dockerfile: Dockerfile
    container_name: kopis-back
    ports:
      - "8080:8080"
  frontend:
    build:
      context: kopis-front
      dockerfile: Dockerfile
    container_name: kopis-front
    depends_on:
      - "backend"
    ports:
      - "3000:3000"

volumes:
  kopisDB: