#mysql(DB) service 실행
apiVersion: v1
kind: Service
metadata:
  name: kopisdb-service
spec:
  selector:
    app: kopisdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30036
  type: NodePort
