apiVersion: v1
kind: Service
metadata:
  name: kopis-back2
spec:
  selector:
    app: kopis-back2
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30083
  type: NodePort
