FROM node:22
WORKDIR /app
COPY package-k8s.json ./package.json
RUN npm install
COPY . .
COPY package-k8s.json ./package.json
RUN npm run build
EXPOSE 3004
ENV REACT_APP_API_URL=http://kopis-back2:8084
ENV REACT_APP_ENV_MODE=k8s
ENV PORT=3004
ENV WDS_SOCKET_PORT=3004
CMD ["npm", "start"]