apiVersion: v1
kind: Service
metadata:
  name: kopis-back
spec:
  selector:
    app: kopis-back
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
