apiVersion: v1
kind: Service
metadata:
  name: kopis-front
spec:
  selector:
    app: kopis-front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30081
  type: NodePort
